### ISSUE TITLE
Missing parts at JLPCB

### ISSUE THREAD

**Issue by msanaullahsahar** [PeterJBurke/Nanostat#11]
Hi,
First let me thank you for the PCB that you have designed. Its amazing. I ordered one from JLCPCB, but I’ve faced constant parts shortages, which have prevented me from completing the order.

Could you please revise the PCB with components that are currently available? This would make it much easier to order from JLCPCB. I know that Exchange offers alternative parts, but unfortunately, many of the missing components do not have suitable alternatives available.

**Missing Parts**

![image](https://github.com/user-attachments/assets/6e6e1827-0654-43e4-94bc-b030f5184647)

**Comment by PeterJBurke** [comment]
Hi. I understand the supply chain problem. 
I don't have time right now to replace all those parts. 
For the LEDs and the MOSFET and capacitor, you should easily be able to find replacements since they are standard size. The antenna is more difficult for me to find a JLCPCB replacement for (there might be one, I just can't find it quickly). However I notice Amazon in the US sells those, so you could hand solder when you get the board.
Alternatively, if you like I can send you as a courtesy  a fully assembled board if you email my university account at pburke@uci.edu.

**Comment by ZenPylon** [comment]
Hi @PeterJBurke, I'm also interested in ordering this board and having it assembled by JLCPCB. In terms of the antenna, would [this](https://jlcpcb.com/partdetail/Walsin_TechCorp-RFANT5220110A0T/C127611) be a suitable replacement? It has the same footprint, though I don't know enough about antennas to compare on the other factors like bandwidth, etc.

If so, I'd be happy to try my hand at replacing the remaining out of stock components, and I could put up a PR for review when I'm done. Thanks!

**Comment by PeterJBurke** [comment]
Please try version 3.5.4 in the gerber files and let me know if that works.
https://github.com/PeterJBurke/Nanostat/tree/master/GerberFiles/Version3dot5dot4
It seems to work for me as of 11/26/2024.

**Comment by msanaullahsahar** [comment]
> Please try version 3.5.4 in the gerber files and let me know if that works. https://github.com/PeterJBurke/Nanostat/tree/master/GerberFiles/Version3dot5dot4 It seems to work for me as of 11/26/2024.

Hi Dr. Burke,

Thank you so much for your hard work and for taking the time to fix this. I successfully placed an order through JLCPCB using the Gerbers from version 3.5.4. Now, I’m looking forward to getting my hands on this new board!
